# If you want to run CAPVCD locally in debug mode, rename this file to service.yaml and backup the original service.yaml
# Below Service definition enables Kubernetes API server to talk to the webhook server running locally on your laptop.

apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443

---
apiVersion: v1
kind: Endpoints
metadata:
  name: webhook-service
  namespace: system
subsets:
  - addresses:
      - ip: 192.168.86.30 # IP address of your local mac/laptop
    ports:
      - port: 9443